# Generated by Django 4.2.5 on 2023-11-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название монеты')),
                ('imag', models.ImageField(upload_to='image/&Y', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date_publ', models.DateField(verbose_name='Дата выхода')),
            ],
        ),
    ]
