# Generated by Django 4.2.5 on 2023-11-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название алгоритма')),
                ('description', models.TextField(blank=True, verbose_name='Описание алгоритма')),
            ],
            options={
                'verbose_name': 'Алгоритм',
                'verbose_name_plural': 'Алгоритмы',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название биржи')),
                ('description', models.TextField(blank=True, verbose_name='Описание биржи')),
            ],
            options={
                'verbose_name': 'Биржа',
                'verbose_name_plural': 'Биржи',
            },
        ),
        migrations.AlterModelOptions(
            name='coin',
            options={'verbose_name': 'Монета', 'verbose_name_plural': 'Монеты'},
        ),
        migrations.AddField(
            model_name='coin',
            name='url',
            field=models.SlugField(default='eth', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='algo',
            field=models.ManyToManyField(to='coins.algo', verbose_name='Алгоритмы'),
        ),
        migrations.AddField(
            model_name='coin',
            name='currency',
            field=models.ManyToManyField(to='coins.currency', verbose_name='Биржи'),
        ),
    ]
