# Generated by Django 4.2.7 on 2023-11-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_algo_currency_alter_coin_options_coin_url_coin_algo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название метода')),
                ('description', models.TextField(blank=True, verbose_name='Описание метода')),
            ],
            options={
                'verbose_name': 'Доказательство работы',
                'verbose_name_plural': 'Доказательство работы',
            },
        ),
        migrations.AlterField(
            model_name='coin',
            name='algo',
            field=models.ManyToManyField(blank=True, to='coins.algo', verbose_name='Алгоритмы'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='currency',
            field=models.ManyToManyField(blank=True, to='coins.currency', verbose_name='Биржи'),
        ),
        migrations.AddField(
            model_name='coin',
            name='proof',
            field=models.ManyToManyField(blank=True, to='coins.proof', verbose_name='Доказательство работы'),
        ),
    ]
