# Generated by Django 4.2.7 on 2023-11-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_proof_alter_coin_algo_alter_coin_currency_coin_proof'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proof',
            new_name='Method',
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'verbose_name': 'Доказательство работы/доли', 'verbose_name_plural': 'Доказательство работы/доли'},
        ),
        migrations.RemoveField(
            model_name='coin',
            name='proof',
        ),
        migrations.AddField(
            model_name='coin',
            name='method',
            field=models.ManyToManyField(blank=True, to='coins.method', verbose_name='Доказательство работы/доли'),
        ),
    ]
