# Generated by Django 4.2.7 on 2023-11-17 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coins", "0004_rename_proof_method_alter_method_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "text",
                    models.TextField(max_length=2000, verbose_name="Текст отзыва"),
                ),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coins.coin",
                        verbose_name="Монета",
                    ),
                ),
            ],
            options={"verbose_name": "Монета", "verbose_name_plural": "Монеты",},
        ),
    ]
